env: "local" # local, dev, prod 

http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 30s

jwt_secret: ""
check_interval: 30m

redis:
  db: 0
  addr: "redis:6379"
  default_ttl: 1m # TTL для кешированных продуктов

rabbitmq:
  url: "amqp://user:password@rabbitmq:5672/"
  queue_name: ""

postgres:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  dbname: "price_monitoring_app"
  sslmode: "disable"